# Lab: Structured and Unstructured Data

<!-- BEGIN QUESTION -->

**Task 1:** Import the pandas library.

In [1]:
import pandas as pd

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

**Task 2**: Load a CSV file `data.csv` into a pandas dataframe named `df`. 
- The CSV file is located in the folder that you downloaded from OWL. 
- Display the first 12 rows of the data.

In [2]:
df = pd.read_csv('data.csv', sep=',', encoding='utf-8')
df.head(12)

,budget,id,original_language,popularity,release_date,revenue,runtime,status,tagline,title,vote_average,vote_count
0,4500000,36419,en,14.570359,2010-04-09,3606395,104.0,Released,Life is the symptom. Death is the cure.,After.Life,5.4,251
1,70000000,6068,en,18.264635,1998-06-12,164000000,98.0,Released,"After this week in paradise, they’re going to ...",Six Days Seven Nights,5.6,332
2,0,19904,en,7.924428,2009-10-16,0,101.0,Released,Daddy's home.,The Stepfather,5.4,167
3,2500000,45132,en,12.204569,2010-09-09,324138,96.0,Released,"Shut up, crime!",Super,6.6,441
4,30000000,9009,en,14.376463,2005-06-27,25473093,105.0,Released,"This Season, The Mystery Of The Darkness Will ...",Dark Water,5.3,274
5,1800000,205126,en,1.959405,2013-06-27,0,86.0,Released,NaN,Independence Daysaster,4.2,22
6,10000000,82532,en,10.409155,2011-09-13,4417580,83.0,Released,The first step to finding your destiny is leav...,"Jeff, Who Lives at Home",6.1,217
7,40000000,1677,en,21.743321,2004-10-29,124731534,152.0,Released,The extraordinary life story of Ray Charles.,Ray,7.2,467
8,30000000,11648,en,11.120167,2005-07-21,58405313,98.0,Released,NaN,Must Love Dogs,5.8,140
9,0,9434,en,13.817269,1997-04-11,28084357,107.0,Released,Even a hit man deserves a second shot.,Grosse Pointe Blank,6.9,275
10,0,20406,en,0.361554,2007-07-07,0,76.0,Released,NaN,Rockaway,5.8,2
11,300000,21525,en,1.314576,2003-01-23,7808524,112.0,Released,In his own words,Tupac: Resurrection,8.0,26

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

**Task 3**: Describe five characteristics or aspects of the dataset. 

- Always support your response with the appropriate code.
- Consider including details such as the size of the data, the columns, data types, statistics about numeric columns, and any other relevant information.

In [3]:
# Description 1: Size of dataset
# The given dataset contains 2000 rows and 12 columns, which means it includes 2000 movies with 12 attributes each (budget, popularity, etc.)

df.shape

(2000, 12)

In [4]:
# Description 2: Column data types
# There's a mix of numeric and categorical columns

# Numeric columns (floats and integers): budget, id, popularity, revenue, runtime, vote_average, vote_count
# Categorical columns (strings): original_language, release_date, status, tagline, title

# Using the following .info() method, we can list out all the data types used in the dataset
df.info()

# Observations:
# There are 4 int64 columns (integers)
# There are 3 float64 columns (floats/decimals)
# There are 5 object columns (string)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             2000 non-null   int64
 1   id                 2000 non-null   int64
 2   original_language  2000 non-null   object
 3   popularity         2000 non-null   float64
 4   release_date       1999 non-null   object
 5   revenue            2000 non-null   int64
 6   runtime            1998 non-null   float64
 7   status             2000 non-null   object
 8   tagline            1646 non-null   object
 9   title              2000 non-null   object
 10  vote_average       2000 non-null   float64
 11  vote_count         2000 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 187.6+ KB

In [5]:
# Description 3: Longest Movies
# We can determine the 5 longest movies by sorting the data by runtime, and set ascending to False. Along with the .head() method

df.sort_values(by='runtime', ascending=False).head()

# Observation: the 5 longest movies in this dataset are:
# 1. Once Upon a Time in America
# 2. Gods and Generals
# 3. The Greatest Story Ever Told
# 4. Intolerance
# 5. Reds

,budget,id,original_language,popularity,release_date,revenue,runtime,status,tagline,title,vote_average,vote_count
1820,30000000,311,en,49.336397,1984-02-16,0,229.0,Released,"Crime, passion and lust for power - Sergio Leo...",Once Upon a Time in America,8.2,1069
468,56000000,16072,en,4.362535,2003-02-21,12923936,214.0,Released,The nations heart was touched by...,Gods and Generals,6.1,48
158,20000000,2428,en,3.011205,1965-02-15,15473333,199.0,Released,NaN,The Greatest Story Ever Told,6.5,41
1629,385907,3059,en,3.232447,1916-09-04,8394751,197.0,Released,The Cruel Hand of Intolerance,Intolerance,7.4,60
126,32000000,18254,en,4.602185,1981-12-25,40382659,195.0,Released,Not since Gone With The Wind has there been a ...,Reds,7.1,67

In [6]:
# Description 4: Statistical Properties of Numeric Columns

# Using the .describe() method, we can get an overview of the information in the dataset (min, max, mean, etc.)
# We can use this information to determine the average budget, average revenue, popularity, highest revenue, etc.

df.describe()

# Observations:
# - Average runtime: 106 minutes
# - Average budget: ~ 2.93 million
# - Highest revenue: ~ 1.845 billion
# - Lowest rating: 0

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,2.000000e+03,2000.000000,2000.000000,2.000000e+03,1998.000000,2000.000000,2000.000000
mean,2.930990e+07,58577.769500,21.571777,8.184755e+07,106.263263,6.080650,673.777500
std,4.130900e+07,89059.602285,36.000351,1.605606e+08,21.609262,1.199433,1227.733648
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,8.500000e+05,9019.750000,4.634092,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,15068.500000,12.466258,1.941763e+07,104.000000,6.200000,223.000000
75%,4.000000e+07,62183.750000,27.875819,9.325544e+07,117.000000,6.800000,703.500000
max,3.800000e+08,459488.000000,875.581305,1.845034e+09,229.000000,10.000000,13752.000000

In [7]:
# Description 5: 3 Least Popular Movies
# We can determine the 3 least popular movies by sorting the data by popularity, and set ascending to True. Along with the .head() method

df.sort_values(by='popularity', ascending=True).head(3)

# Observation: the least 3 popular movies in this dataset are America Is Still the Place, Alien Zone and Penitentiary

,budget,id,original_language,popularity,release_date,revenue,runtime,status,tagline,title,vote_average,vote_count
1470,0,380097,en,0.000000,NaN,0,0.0,Released,NaN,America Is Still the Place,0.0,0
1796,0,77156,en,0.000372,1978-11-22,0,90.0,Released,Don't you dare go in there!,Alien Zone,4.0,3
241,0,65448,en,0.001117,1979-12-01,0,99.0,Released,"There's only one way out, and 100 fools stand ...",Penitentiary,4.9,8

<!-- END QUESTION -->

**Task 4**: Delete all non-numeric columns from the DataFrame `df`, except from the `title`.

In [8]:
df = df.drop(columns=['original_language', 'release_date', 'status', 'status', 'tagline'])
df.columns

Index(['budget', 'id', 'popularity', 'revenue', 'runtime', 'title',
       'vote_average', 'vote_count'],
      dtype='object')

**Task 5**: Rename the column `runtime` by `runtime(min)` in the DataFrame `df` to specify that the values in that column are expressed in minutes.

In [9]:
df = df.rename(columns={'runtime': 'runtime(min)'})
df.columns

Index(['budget', 'id', 'popularity', 'revenue', 'runtime(min)', 'title',
       'vote_average', 'vote_count'],
      dtype='object')

**Task 6**: Create a new column in the DataFrame `df` that computes the profit by minutes for each movie. 
 - The profit can be computed as the difference between the revenue and the budget. See the lecture. 
 - The new column must be named `profit_by_min`.
 - Display the first 5 columns of the resulting `df`.

In [10]:
df['profit_by_min'] = (df['revenue'] - df['budget']) / df['runtime(min)']
df.head()

,budget,id,popularity,revenue,runtime(min),title,vote_average,vote_count,profit_by_min
0,4500000,36419,14.570359,3606395,104.0,After.Life,5.4,251,-8592.355769
1,70000000,6068,18.264635,164000000,98.0,Six Days Seven Nights,5.6,332,959183.673469
2,0,19904,7.924428,0,101.0,The Stepfather,5.4,167,0.000000
3,2500000,45132,12.204569,324138,96.0,Super,6.6,441,-22665.229167
4,30000000,9009,14.376463,25473093,105.0,Dark Water,5.3,274,-43113.400000

**Task 7**: Sort the DataFrame `df` by budget in descending order and assign the result to a new DataFrame named `sort_df`.

In [11]:
sort_df = df.sort_values(by='budget', ascending=False)
sort_df

,budget,id,popularity,revenue,runtime(min),title,vote_average,vote_count,profit_by_min
1946,380000000,1865,135.413856,1045713802,136.0,Pirates of the Caribbean: On Stranger Tides,6.4,4948,4.894954e+06
1456,270000000,1452,57.925623,391081192,154.0,Superman Returns,5.4,1400,7.862415e+05
1283,260000000,38757,48.681969,591794936,100.0,Tangled,7.4,3330,3.317949e+06
179,258000000,559,115.699814,890871626,139.0,Spider-Man 3,5.9,3576,4.553033e+06
549,250000000,767,98.885637,933959197,153.0,Harry Potter and the Half-Blood Prince,7.4,5293,4.470322e+06
...,...,...,...,...,...,...,...,...,...
817,0,29371,1.708190,0,94.0,The Incredibly True Adventure of Two Girls In ...,5.7,13,0.000000e+00
1590,0,318040,0.583446,0,99.0,Bizarre,6.2,11,0.000000e+00
831,0,9900,9.974681,6538177,94.0,Grandma's Boy,6.6,220,6.955507e+04
832,0,19204,8.022122,0,87.0,The Beyond,6.6,117,0.000000e+00
661,0,110683,0.289433,0,98.0,The Wicked Lady,4.3,4,0.000000e+00

**Task 8**: Extract a segment of 12 movies from the original DataFrame `df`, starting at index 1000, and assign the result to the variable `segment_df`. Show the `segment_df`.

In [12]:
segment_df = df[1000:1012] # start at 1000, then show the next 12
segment_df

,budget,id,popularity,revenue,runtime(min),title,vote_average,vote_count,profit_by_min
1000,10,217708,1.617943,11,85.0,Of Horses and Men,6.9,26,0.011765
1001,7000000,13685,11.700578,560069,91.0,Bottle Rocket,6.8,281,-70768.472527
1002,19800000,239678,20.311684,41296320,103.0,This Is Where I Leave You,6.5,505,208702.135922
1003,45000000,9899,6.803965,38058335,134.0,The Producers,6.1,151,-51803.470149
1004,55000000,175574,14.414937,110000000,91.0,Free Birds,5.7,254,604395.604396
1005,0,270554,0.053755,0,85.0,Echo Dr.,5.0,1,0.000000
1006,0,37737,4.807549,0,131.0,Kites,6.0,40,0.000000
1007,4500000,9303,15.359952,7011317,108.0,Bound,6.9,198,23252.935185
1008,75000000,8970,4.842626,29000000,90.0,The Out-of-Towners,5.0,45,-511111.111111
1009,17000000,114150,32.746486,115350426,112.0,Pitch Perfect,7.3,2247,878128.803571
1010,9500000,667,28.675891,111584787,117.0,You Only Live Twice,6.5,531,872519.547009
1011,100000000,11688,51.113717,169327687,78.0,The Emperor's New Groove,7.2,1490,888816.500000